package dev.nstv.practicalfilament.theme

import androidx.compose.ui.graphics.Color

val slidesBackground = Color(0xFFFFFFFF)

object TileColor {
    val Blue = Color(0xFF00A2FF)
    val Pink = Color(0xFFFF42A1)
    val Purple = Color(0xFF7A81FF)
    val Green = Color(0xFF3DDC84)
    val Magenta = Color(0xFFC51162)
    val Yellow = Color(0xFFFFEB3B)
    val Orange = Color(0xFFFF9800)
    val Red = Color(0xFFFF0000)
    val DarkGreen = Color(0xFF24804D)
    val LightGray = Color(0xFFCCCCCC)
    val DarkGray = Color(0xFF444444)

    val list = listOf(
        Blue,
        Pink,
        Purple,
        Green,
        Magenta,
        Yellow,
        Orange,
        Red,
        DarkGreen,
        LightGray,
        DarkGray,
    )

    val map = mapOf<String, Color>(
        "Blue" to Blue,
        "Pink" to Pink,
        "Purple" to Purple,
        "Green" to Green,
        "Magenta" to Magenta,
        "Yellow" to Yellow,
        "Orange" to Orange,
        "Red" to Red,
        "DarkGreen" to DarkGreen,
        "LightGray" to LightGray,
        "DarkGray" to DarkGray,
    )

    fun random() = list.random()
    fun randomFilter(filter: Color) = list.filter { it != filter }.random()
}

val seed = Color(0xFF0072E4)

val primaryLight = Color(0xFF005AB6)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF0072E4)
val onPrimaryContainerLight = Color(0xFFFEFCFF)
val secondaryLight = Color(0xFF465F8B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFB4CCFF)
val onSecondaryContainerLight = Color(0xFF3D5682)
val tertiaryLight = Color(0xFF8935A8)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFA550C3)
val onTertiaryContainerLight = Color(0xFFFFFCFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF9F9FF)
val onBackgroundLight = Color(0xFF181C23)
val surfaceLight = Color(0xFFF9F9FF)
val onSurfaceLight = Color(0xFF181C23)
val surfaceVariantLight = Color(0xFFDDE2F2)
val onSurfaceVariantLight = Color(0xFF414753)
val outlineLight = Color(0xFF717785)
val outlineVariantLight = Color(0xFFC1C6D6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3038)
val inverseOnSurfaceLight = Color(0xFFEFF0FA)
val inversePrimaryLight = Color(0xFFABC7FF)
val surfaceDimLight = Color(0xFFD8DAE3)
val surfaceBrightLight = Color(0xFFF9F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F3FD)
val surfaceContainerLight = Color(0xFFECEDF7)
val surfaceContainerHighLight = Color(0xFFE6E8F2)
val surfaceContainerHighestLight = Color(0xFFE0E2EC)

val primaryLightMediumContrast = Color(0xFF003570)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF006BD6)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF1B3660)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF556D9B)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF5C007A)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF9C48BA)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF9F9FF)
val onBackgroundLightMediumContrast = Color(0xFF181C23)
val surfaceLightMediumContrast = Color(0xFFF9F9FF)
val onSurfaceLightMediumContrast = Color(0xFF0E1118)
val surfaceVariantLightMediumContrast = Color(0xFFDDE2F2)
val onSurfaceVariantLightMediumContrast = Color(0xFF313642)
val outlineLightMediumContrast = Color(0xFF4D525F)
val outlineVariantLightMediumContrast = Color(0xFF676D7B)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2D3038)
val inverseOnSurfaceLightMediumContrast = Color(0xFFEFF0FA)
val inversePrimaryLightMediumContrast = Color(0xFFABC7FF)
val surfaceDimLightMediumContrast = Color(0xFFC4C6D0)
val surfaceBrightLightMediumContrast = Color(0xFFF9F9FF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF2F3FD)
val surfaceContainerLightMediumContrast = Color(0xFFE6E8F2)
val surfaceContainerHighLightMediumContrast = Color(0xFFDBDCE6)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCFD1DB)

val primaryLightHighContrast = Color(0xFF002B5D)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF004793)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF0E2C55)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF304974)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF4D0066)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF741D93)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF9F9FF)
val onBackgroundLightHighContrast = Color(0xFF181C23)
val surfaceLightHighContrast = Color(0xFFF9F9FF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDDE2F2)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF262C38)
val outlineVariantLightHighContrast = Color(0xFF444956)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2D3038)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFABC7FF)
val surfaceDimLightHighContrast = Color(0xFFB6B8C2)
val surfaceBrightLightHighContrast = Color(0xFFF9F9FF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEFF0FA)
val surfaceContainerLightHighContrast = Color(0xFFE0E2EC)
val surfaceContainerHighLightHighContrast = Color(0xFFD2D4DE)
val surfaceContainerHighestLightHighContrast = Color(0xFFC4C6D0)

val primaryDark = Color(0xFFABC7FF)
val onPrimaryDark = Color(0xFF002F65)
val primaryContainerDark = Color(0xFF0072E4)
val onPrimaryContainerDark = Color(0xFFFEFCFF)
val secondaryDark = Color(0xFFAEC7F9)
val onSecondaryDark = Color(0xFF14305A)
val secondaryContainerDark = Color(0xFF2D4772)
val onSecondaryContainerDark = Color(0xFF9DB6E7)
val tertiaryDark = Color(0xFFEEB1FF)
val onTertiaryDark = Color(0xFF53006F)
val tertiaryContainerDark = Color(0xFFA550C3)
val onTertiaryContainerDark = Color(0xFFFFFCFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF10131A)
val onBackgroundDark = Color(0xFFE0E2EC)
val surfaceDark = Color(0xFF10131A)
val onSurfaceDark = Color(0xFFE0E2EC)
val surfaceVariantDark = Color(0xFF414753)
val onSurfaceVariantDark = Color(0xFFC1C6D6)
val outlineDark = Color(0xFF8B919F)
val outlineVariantDark = Color(0xFF414753)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE0E2EC)
val inverseOnSurfaceDark = Color(0xFF2D3038)
val inversePrimaryDark = Color(0xFF005CBB)
val surfaceDimDark = Color(0xFF10131A)
val surfaceBrightDark = Color(0xFF363941)
val surfaceContainerLowestDark = Color(0xFF0B0E15)
val surfaceContainerLowDark = Color(0xFF181C23)
val surfaceContainerDark = Color(0xFF1C2027)
val surfaceContainerHighDark = Color(0xFF272A31)
val surfaceContainerHighestDark = Color(0xFF32353C)

val primaryDarkMediumContrast = Color(0xFFCDDDFF)
val onPrimaryDarkMediumContrast = Color(0xFF002551)
val primaryContainerDarkMediumContrast = Color(0xFF428FFF)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFCDDDFF)
val onSecondaryDarkMediumContrast = Color(0xFF05254E)
val secondaryContainerDarkMediumContrast = Color(0xFF7891C1)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFF7CFFF)
val onTertiaryDarkMediumContrast = Color(0xFF420059)
val tertiaryContainerDarkMediumContrast = Color(0xFFC46DE2)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF10131A)
val onBackgroundDarkMediumContrast = Color(0xFFE0E2EC)
val surfaceDarkMediumContrast = Color(0xFF10131A)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF414753)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD7DCEC)
val outlineDarkMediumContrast = Color(0xFFACB2C1)
val outlineVariantDarkMediumContrast = Color(0xFF8B909F)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE0E2EC)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF272A31)
val inversePrimaryDarkMediumContrast = Color(0xFF004691)
val surfaceDimDarkMediumContrast = Color(0xFF10131A)
val surfaceBrightDarkMediumContrast = Color(0xFF41444C)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF05070E)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1A1E25)
val surfaceContainerDarkMediumContrast = Color(0xFF25282F)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2F333A)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3B3E45)

val primaryDarkHighContrast = Color(0xFFEBF0FF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFA4C3FF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000B21)
val secondaryDarkHighContrast = Color(0xFFEBF0FF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFAAC3F5)
val onSecondaryContainerDarkHighContrast = Color(0xFF000B21)
val tertiaryDarkHighContrast = Color(0xFFFFEAFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFECABFF)
val onTertiaryContainerDarkHighContrast = Color(0xFF190024)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF10131A)
val onBackgroundDarkHighContrast = Color(0xFFE0E2EC)
val surfaceDarkHighContrast = Color(0xFF10131A)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF414753)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFEBF0FF)
val outlineVariantDarkHighContrast = Color(0xFFBDC2D2)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE0E2EC)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF004691)
val surfaceDimDarkHighContrast = Color(0xFF10131A)
val surfaceBrightDarkHighContrast = Color(0xFF4D5058)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1C2027)
val surfaceContainerDarkHighContrast = Color(0xFF2D3038)
val surfaceContainerHighDarkHighContrast = Color(0xFF383B43)
val surfaceContainerHighestDarkHighContrast = Color(0xFF44474F)
